name: nested_navigation_with_getx_and_bottomnavigationbar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: ^4.6.5

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

